default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: tqv
  password: vns2_513

development:
  <<: *default
  database: shoes-dev

test:
  <<: *default
  database: shoes-test

production:
  <<: *default
  database: shoes-production
